package main

import (
	"bytes"
	"io"
)

// filterCSIu copies data from src to dst, stripping CSI u sequences.
//
// CSI u is a terminal protocol that encodes key events (arrows, function keys,
// modifiers) as escape sequences like ESC [ < 3 5 ; 5 u. When a user types
// in raw terminal mode (-interactive), these sequences are generated by the
// user's terminal and must be stripped before forwarding to the PTY, otherwise
// the client process sees raw escape artifacts.
//
// The filter tracks a simple state machine: when it sees ESC [ < it buffers all
// subsequent bytes until a terminating 'u' (CSI u) or any byte that breaks the
// pattern, then either discards the sequence or flushes the buffer as-is.
func filterCSIu(dst io.Writer, src io.Reader) (written int64, err error) {
	buf := make([]byte, 4096)
	var pending bytes.Buffer
	state := 0 // 0=normal, 1=ESC seen, 2=ESC [ seen, 3=CSI u params

	for {
		n, rerr := src.Read(buf)
		if n > 0 {
			data := buf[:n]
			for _, b := range data {
				switch state {
				case 0: // normal
					if b == 0x1B {
						pending.Reset()
						pending.WriteByte(b)
						state = 1
					} else {
						nw, werr := dst.Write([]byte{b})
						written += int64(nw)
						if werr != nil {
							return written, werr
						}
					}

				case 1: // ESC seen, expect '['
					pending.WriteByte(b)
					if b == '[' {
						state = 2
					} else {
						nw, werr := dst.Write(pending.Bytes())
						written += int64(nw)
						if werr != nil {
							return written, werr
						}
						pending.Reset()
						state = 0
					}

				case 2: // ESC [ seen, expect '<'
					pending.WriteByte(b)
					if b == '<' {
						state = 3
					} else {
						nw, werr := dst.Write(pending.Bytes())
						written += int64(nw)
						if werr != nil {
							return written, werr
						}
						pending.Reset()
						state = 0
					}

				case 3: // CSI u params: digits, semicolons, terminating 'u'
					if b == 'u' {
						pending.Reset()
						state = 0
					} else if b >= '0' && b <= '9' || b == ';' {
						pending.WriteByte(b)
					} else if b == 0x1B {
						nw, werr := dst.Write(pending.Bytes())
						written += int64(nw)
						if werr != nil {
							return written, werr
						}
						pending.Reset()
						pending.WriteByte(b)
						state = 1
					} else {
						pending.WriteByte(b)
						nw, werr := dst.Write(pending.Bytes())
						written += int64(nw)
						if werr != nil {
							return written, werr
						}
						pending.Reset()
						state = 0
					}
				}
			}
		}
		if rerr != nil {
			if rerr == io.EOF && pending.Len() > 0 {
				nw, werr := dst.Write(pending.Bytes())
				written += int64(nw)
				if werr != nil {
					return written, werr
				}
			}
			return written, rerr
		}
	}
}
