package main

import (
	"bytes"
	"context"
	"flag"
	"io"
	"log/slog"
	"os"
	"os/signal"
	"syscall"
	"time"

	"github.com/romayengineer/loopai-mcp/internal/launcher"
	"github.com/romayengineer/loopai-mcp/internal/proto"
	"golang.org/x/term"
)

const defaultIdleTimeout = 5 * time.Second

func main() {
	client := flag.String("client", defaultClient(), "client binary to spawn (claude, opencode, etc.)")
	socketPath := flag.String("socket", proto.DefaultSocketPath(), "unix socket path")
	idleTimeout := flag.Duration("idle", defaultIdleTimeout, "idle timeout before signaling backend")
	passthrough := flag.Bool("passthrough", false, "show PTY output on terminal")
	interactive := flag.Bool("interactive", false, "interactive mode: stdin -> PTY, PTY -> terminal (implies -passthrough)")
	flag.Parse()

	slog.SetDefault(slog.New(slog.NewTextHandler(os.Stderr, nil)))

	conn, err := proto.Connect(*socketPath)
	if err != nil {
		slog.Error("backend not running — start it with 'loopai-backend'", "error", err)
		os.Exit(1)
	}
	pc := proto.NewConn(conn)

	args := flag.Args()
	if args == nil {
		args = []string{}
	}

	proc, err := launcher.Spawn(*client, args)
	if err != nil {
		pc.Close()
		slog.Error("spawn client", "client", *client, "error", err)
		os.Exit(1)
	}

	// Disable PTY echo when interactive, so raw keystrokes forwarded from
	// stdin don't get echoed back as escape sequences (e.g. ^[[<35u).
	// See launcher.DisablePTYEcho docs for details.
	if *interactive {
		if err := proc.DisablePTYEcho(); err != nil {
			slog.Warn("disable PTY echo", "error", err)
		}
	}

	ctx, cancel := context.WithCancel(context.Background())
	defer cancel()
	defer pc.Close()
	defer proc.Close()

	sigCh := make(chan os.Signal, 1)
	signal.Notify(sigCh, syscall.SIGINT, syscall.SIGTERM)
	go func() {
		sig := <-sigCh
		slog.Info("shutting down", "signal", sig)
		cancel()
		pc.Close()
	}()

	msg, err := proto.NewMessage(proto.MsgStarted, proto.StartedPayload{
		Pid:    proc.PID(),
		Client: *client,
	})
	if err != nil {
		slog.Warn("marshal started", "error", err)
	} else if err := pc.Send(ctx, msg); err != nil {
		slog.Warn("send started", "error", err)
	}

	idle := launcher.NewIdleDetector(*idleTimeout, func() {
		msg, mErr := proto.NewMessage(proto.MsgIdle, proto.IdlePayload{})
		if mErr != nil {
			slog.Warn("marshal idle", "error", mErr)
			return
		}
		if err := pc.Send(ctx, msg); err != nil {
			slog.Warn("send idle", "error", err)
		}
	})
	idle.Start()

	// Interactive mode: forward stdin -> PTY and enable passthrough
	if *interactive {
		*passthrough = true

		if term.IsTerminal(int(os.Stdin.Fd())) {
			oldState, err := term.MakeRaw(int(os.Stdin.Fd()))
			if err != nil {
				slog.Error("raw terminal", "error", err)
			} else {
				defer func() {
					if err := term.Restore(int(os.Stdin.Fd()), oldState); err != nil {
						slog.Warn("restore terminal", "error", err)
					}
				}()
			}
		}

		go func() {
			written, err := filterCSIu(proc, os.Stdin)
			if err != nil {
				slog.Warn("stdin filter", "written", written, "error", err)
			}
		}()
	}

	// Wrap the PTY reader with optional passthrough to terminal
	r := io.Reader(proc)
	if *passthrough {
		r = io.TeeReader(proc, os.Stdout)
	}

	errCh := make(chan error, 2)
	go func() {
		err := launcher.PipePTYToBackend(ctx, pc, r, idle)
		errCh <- err
	}()
	go func() {
		err := launcher.PipeBackendToPTY(ctx, pc, proc)
		errCh <- err
	}()

	<-errCh
	idle.Stop()

	// Tell PipeBackendToPTY to stop before sending the exit message,
	// otherwise it may still be blocked on Receive, causing a data race.
	shutdownMsg, sErr := proto.NewMessage(proto.MsgShutdown, proto.ShutdownPayload{})
	if sErr != nil {
		slog.Warn("marshal shutdown", "error", sErr)
	} else if err := pc.Send(ctx, shutdownMsg); err != nil {
		slog.Warn("send shutdown", "error", err)
	}
	<-errCh

	<-proc.Wait()
	exitCode := proc.ExitCode()

	msg, err = proto.NewMessage(proto.MsgExited, proto.ExitedPayload{
		Code: exitCode,
	})
	if err != nil {
		slog.Warn("marshal exited", "error", err)
	} else if err := pc.Send(ctx, msg); err != nil {
		slog.Warn("send exited", "error", err)
	}

	if exitCode != 0 {
		slog.Warn("client exited", "code", exitCode)
		os.Exit(exitCode)
	}
}

func defaultClient() string {
	if c := os.Getenv("LOOPAI_CLIENT"); c != "" {
		return c
	}
	return "claude"
}

// filterCSIu copies data from src to dst, stripping CSI u sequences.
//
// CSI u is a terminal protocol that encodes key events (arrows, function keys,
// modifiers) as escape sequences like ESC [ < 3 5 ; 5 u. When a user types
// in raw terminal mode (-interactive), these sequences are generated by the
// user's terminal and must be stripped before forwarding to the PTY, otherwise
// the client process sees raw escape artifacts.
//
// The filter tracks a simple state machine: when it sees ESC [ < it buffers all
// subsequent bytes until a terminating 'u' (CSI u) or any byte that breaks the
// pattern, then either discards the sequence or flushes the buffer as-is.
func filterCSIu(dst io.Writer, src io.Reader) (written int64, err error) {
	buf := make([]byte, 4096)
	var pending bytes.Buffer
	state := 0 // 0=normal, 1=ESC seen, 2=ESC [ seen, 3=CSI u params

	for {
		n, rerr := src.Read(buf)
		if n > 0 {
			data := buf[:n]
			for _, b := range data {
				switch state {
				case 0: // normal
					if b == 0x1B {
						pending.Reset()
						pending.WriteByte(b)
						state = 1
					} else {
						nw, werr := dst.Write([]byte{b})
						written += int64(nw)
						if werr != nil {
							return written, werr
						}
					}

				case 1: // ESC seen, expect '['
					pending.WriteByte(b)
					if b == '[' {
						state = 2
					} else {
						// Not a CSI sequence, flush pending and discard
						nw, werr := dst.Write(pending.Bytes())
						written += int64(nw)
						if werr != nil {
							return written, werr
						}
						pending.Reset()
						state = 0
					}

				case 2: // ESC [ seen, expect '<'
					pending.WriteByte(b)
					if b == '<' {
						state = 3
					} else {
						// Not CSI u, flush pending and discard
						nw, werr := dst.Write(pending.Bytes())
						written += int64(nw)
						if werr != nil {
							return written, werr
						}
						pending.Reset()
						state = 0
					}

				case 3: // CSI u params: digits, semicolons, terminating 'u'
					if b == 'u' {
						// Complete CSI u sequence — discard it
						pending.Reset()
						state = 0
					} else if b >= '0' && b <= '9' || b == ';' {
						// Parameter byte, keep buffering
						pending.WriteByte(b)
					} else if b == 0x1B {
						// Nested ESC — flush pending and restart
						nw, werr := dst.Write(pending.Bytes())
						written += int64(nw)
						if werr != nil {
							return written, werr
						}
						pending.Reset()
						pending.WriteByte(b)
						state = 1
					} else {
						// Unexpected byte — flush pending (including this byte)
						pending.WriteByte(b)
						nw, werr := dst.Write(pending.Bytes())
						written += int64(nw)
						if werr != nil {
							return written, werr
						}
						pending.Reset()
						state = 0
					}
				}
			}
		}
		if rerr != nil {
			// Flush any remaining partial sequence on EOF
			if rerr == io.EOF && pending.Len() > 0 {
				nw, werr := dst.Write(pending.Bytes())
				written += int64(nw)
				if werr != nil {
					return written, werr
				}
			}
			return written, rerr
		}
	}
}
