version: "2"
linters:
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - misspell
  exclusions:
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - _test\.go$
formatters:
  enable:
    - gofmt
    - gci
  settings:
    gofmt:
      simplify: true
  exclusions:
    paths:
      - _test\.go$
